version: '3.7'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
    networks:
      - proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  howto:
    image: docker/getting-started
    networks:
      - proxy
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.howto.rule=Host(`howto.docker.localhost`)"

  whoami:
    image: traefik/whoami 
    networks:
      - proxy
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

networks:
  proxy:
