version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command: [
      --api.insecure=true,
      --providers.docker
    ]
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  howto:
    image: docker/getting-started
    networks:
      - proxy
    labels:
      - "traefik.http.routers.howto.rule=Host(`howto.docker.localhost`)"
networks:
  proxy:
