version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker
      - --entrypoints.web.address=:80
    networks:
      - proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"

  howto:
    image: docker/getting-started
    networks:
      - proxy
    labels:
      - "traefik.http.routers.howto.rule=Host(`howto.docker.localhost`)"
networks:
  proxy:
